name: 4levels
favicon: null
layout_spectrum: 0.95316
typography_spectrum: 0.3901557456701994
title: 'Freelance IT allrounder, specialized in OpenSource'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1836'
    - '#91605c'
    - '#bc9a91'
    - '#6d9efd'
    - '#e7d2b5'
  brandStrength: 0.4375
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
