name: 4levels
favicon: null
layout_spectrum: 0.4361855327151716
typography_spectrum: 0.3901557456701994
title: 'Freelance IT allrounder, specialized in OpenSource'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3687120347749442
  lightness: 0.32953761983662844
  saturation: 0.5827239537611604
  rhythmicContrast: 0.09598181582987309
purpose: []
