analytics: {}
color:
  brandColors:
    - '#D0C0A0'
    - '#000000'
    - '#A07078'
    - '#000000'
    - '#F8D0D8'
  brandStrength: 0.4375
  lightness: 0.75
  rhythmicContrast: 0.25
  saturation: 0.3125
cta: {}
layout_spectrum: 0.95316
name: 4levels
opengraph: {}
purpose: []
typography_spectrum: 0.096846
