analytics: {}
color:
  brandColors:
    - '#C0C0D0'
    - '#203965'
    - '#5078A0'
    - '#284880'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.75
  rhythmicContrast: 0.25
  saturation: 0.3125
cta: {}
layout_spectrum: 0.95316
name: 4levels
opengraph: {}
purpose: []
typography_spectrum: 0
